framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: false
  http_method_override: false
  handle_all_throwables: true
  session: false
  default_locale: 'es'
  serializer:
    enabled: true
  validation:
    enable_attributes: true
  router:
    utf8: true
  mailer:
    dsn: '%env(MAILER_DSN)%'
  cache:
    app: cache.adapter.filesystem
    default_redis_provider: '%env(REDIS_URL)%'
