framework:
  messenger:
    transports:
      async:
        dsn: '%env(REDIS_URL)%/messages'
        retry_strategy:
          max_retries: 5
          delay: 1000
          multiplier: 2
          max_delay: 60000
      failed: '%env(REDIS_URL)%/failed'
    failure_transport: failed
    routing:
      'App\Message\ImportUsersMessage': async
