nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/': ~
